name: build-test
on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.13.x
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
        with:
          args: --verbose
          version: latest
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.13.x
      - uses: actions/checkout@v2
      - name: Build
        run: go build .
      - name: Test
        run: go test -v .
